In [9]:
!pip install -q -U ipython ipython-sql

from IPython.core.display import HTML
HTML("<script>Jupyter.notebook.kernel.restart()</script>")

In [3]:
pip install pandas

Collecting pandas
  Using cached pandas-2.2.3-cp312-cp312-macosx_10_9_x86_64.whl.metadata (89 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.1.2-cp312-cp312-macosx_14_0_x86_64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Using cached pandas-2.2.3-cp312-cp312-macosx_10_9_x86_64.whl (12.5 MB)
Using cached numpy-2.1.2-cp312-cp312-macosx_14_0_x86_64.whl (6.6 MB)
Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.1.2 pandas-2.2.3 pytz-2024.2 tzdata-2024.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import sqlite3 as sql
import pandas as pd
import numpy as np

In [2]:
!kaggle datasets download -d nishaanamin/march-madness-data

Dataset URL: https://www.kaggle.com/datasets/nishaanamin/march-madness-data
License(s): CC0-1.0
Downloading march-madness-data.zip to /Users/branavanjegatheeswaran/Documents/Coding/ball
 80%|██████████████████████████████▎       | 1.00M/1.25M [00:00<00:00, 7.66MB/s]
100%|██████████████████████████████████████| 1.25M/1.25M [00:00<00:00, 4.90MB/s]

In [2]:

rate = pd.read_csv('m_madness/538 Ratings.csv')
data = pd.read_csv('m_madness/KenPom Barttorvik.csv')
heat = pd.read_csv('m_madness/Heat Check Tournament Index.csv')
loc = pd.read_csv('m_madness/Tournament Locations.csv')
shot = pd.read_csv('m_madness/Shooting Splits.csv')
res = pd.read_csv('m_madness/Resumes.csv')
team = pd.read_csv('m_madness/Team Results.csv')
seed = pd.read_csv('m_madness/Seed Results.csv')

In [3]:
data

,YEAR,CONF,CONF ID,QUAD NO,QUAD ID,TEAM NO,TEAM ID,TEAM,SEED,ROUND,...,BADJT RANK,AVG HGT RANK,EFF HGT RANK,EXP RANK,TALENT RANK,FT% RANK,OP FT% RANK,PPPO RANK,PPPD RANK,ELITE SOS RANK
0,2024,MAC,17,61,1,1079,2,Akron,14,0,...,276,238,199,19,176,164,47,122,51,249
1,2024,SEC,28,63,3,1078,3,Alabama,4,0,...,13,33,8,156,106,10,314,2,263,7
2,2024,P12,24,63,3,1077,8,Arizona,2,0,...,16,50,37,196,7,195,134,8,14,47
3,2024,SEC,28,64,4,1076,12,Auburn,4,0,...,58,86,76,127,69,59,284,12,8,69
4,2024,B12,7,63,3,1075,14,Baylor,3,0,...,274,31,22,304,34,97,254,15,155,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1074,2008,BE,8,1,1,5,235,West Virginia,7,16,...,225,18,115,181,61,209,16,22,32,49
1075,2008,SB,26,1,1,4,236,Western Kentucky,12,16,...,111,160,179,55,131,127,214,27,28,203
1076,2008,BSth,10,4,4,3,239,Winthrop,13,64,...,301,231,206,89,236,339,190,170,12,179
1077,2008,B10,6,3,3,2,240,Wisconsin,3,16,...,301,51,35,98,12,118,117,60,2,57
1078,2008,A10,1,1,1,1,244,Xavier,3,8,...,225,149,92,63,147,20,86,4,44,85

In [4]:
for set in [rate, heat, loc, shot]:
    data = pd.merge(data, set, on='TEAM NO', how='outer', suffixes = (None, "_y"))
    for column in data.columns:
        if "_y" in column:
            print(column)
            data = data.drop(columns=column)

YEAR_y
TEAM_y
SEED_y
ROUND_y
YEAR_y
TEAM_y
SEED_y
ROUND_y
YEAR_y
TEAM_y
SEED_y
ROUND_y
YEAR_y
TEAM ID_y
TEAM_y
CONF_y

In [102]:
for column in data.columns:
    if "_x" in column:
        data = data.rename(columns= {column : column[:-2]})

In [5]:
dd = data.copy()

In [197]:
pd.reset_option('display.max_rows')

In [6]:
dd.drop_duplicates()

,YEAR,CONF,CONF ID,QUAD NO,QUAD ID,TEAM NO,TEAM ID,TEAM,SEED,ROUND,...,CLOSE TWOS FG%D RANK,CLOSE TWOS D SHARE RANK,FARTHER TWOS FG% RANK,FARTHER TWOS SHARE RANK,FARTHER TWOS FG%D RANK,FARTHER TWOS D SHARE RANK,THREES FG% RANK,THREES SHARE RANK,THREES FG%D RANK,THREES D SHARE RANK
0,2008,A10,1,1,1,1,244,Xavier,3,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2008,A10,1,1,1,1,244,Xavier,3,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2008,A10,1,1,1,1,244,Xavier,3,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2008,A10,1,1,1,1,244,Xavier,3,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2008,B10,6,3,3,2,240,Wisconsin,3,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2084,2024,P12,24,63,3,1077,8,Arizona,2,0,...,158.0,17.0,234.0,241.0,154.0,328.0,23.0,295.0,149.0,219.0
2085,2024,SEC,28,63,3,1078,3,Alabama,4,0,...,265.0,218.0,299.0,361.0,106.0,185.0,40.0,19.0,67.0,164.0
2086,2024,SEC,28,63,3,1078,3,Alabama,4,0,...,265.0,218.0,299.0,361.0,106.0,185.0,40.0,19.0,67.0,164.0
2087,2024,SEC,28,63,3,1078,3,Alabama,4,0,...,265.0,218.0,299.0,361.0,106.0,185.0,40.0,19.0,67.0,164.0
2088,2024,MAC,17,61,1,1079,2,Akron,14,0,...,179.0,209.0,31.0,205.0,239.0,195.0,276.0,71.0,14.0,170.0

In [7]:
def prev_finder(row, dd, selector):
    year = row["YEAR"]
    team = row["TEAM ID"]
    if year == 2021:
        year -= 1
    if not dd[dd["YEAR"]==(year-1)].empty:
        val = dd[(dd["YEAR"]==(year-1)) & (dd["TEAM ID"] == team)][selector]
        if not val.empty:
            return dd[(dd["YEAR"]==(year-1)) & (dd["TEAM ID"] == team)][selector].iloc[0]
        else:
            if selector == "ROUND":
                return 128
            else:
                return 17
    else:
        return "NaN"


ddd=dd.copy()
ddd=ddd.drop_duplicates()

In [8]:
ddd["PREV SEED"] = ddd.apply(lambda row: prev_finder(row, ddd, "SEED"), axis=1)
ddd["PREV ROUND"] = ddd.apply(lambda row: prev_finder(row, ddd, "ROUND"), axis=1)

In [9]:
seed

,SEED,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,CHAMP%
0,1,16.4,1,-6.4,14,240,191,49,0.796,60,58,48,36,22,16,11,60,99.90%
1,11,11.9,2,13.7,1,112,52,60,0.464,60,29,15,5,3,0,0,0,11.40%
2,3,7.9,3,5.1,3,175,116,59,0.663,60,53,36,18,5,3,1,0,78.50%
3,15,4.4,4,5.7,2,72,12,60,0.167,60,7,4,1,0,0,0,0,0.00%
4,7,3.6,5,2.9,5,116,57,59,0.491,60,36,12,4,3,1,1,0,21.20%
5,12,3.2,6,2.6,6,93,33,60,0.355,60,24,8,1,0,0,0,0,4.50%
6,8,2.3,7,4.6,4,108,48,60,0.444,60,32,7,3,3,3,0,0,15.00%
7,4,1.6,8,2.2,8,154,95,59,0.617,60,46,32,9,5,2,1,0,72.20%
8,16,-1.0,9,1.2,9,62,2,60,0.032,60,2,0,0,0,0,0,0,0.00%
9,9,-1.3,10,2.3,7,99,39,60,0.394,60,28,5,4,2,0,0,0,11.70%
10,13,-3.0,11,1.0,10,76,16,60,0.211,60,14,2,0,0,0,0,0,0.60%
11,2,-6.2,12,-9.7,15,189,130,59,0.688,60,53,37,25,11,3,1,60,96.90%
12,14,-7.3,13,-2.5,13,67,7,60,0.104,60,7,0,0,0,0,0,0,0.50%
13,10,-7.3,13,-1.7,12,95,35,60,0.368,60,24,7,3,1,0,0,0,13.20%
14,5,-8.7,15,-1.5,11,128,68,60,0.531,60,36,18,7,5,2,0,0,49.40%
15,6,-18.6,16,-19.6,16,104,44,60,0.423,60,31,9,4,0,0,0,0,29.30%

In [10]:
test = ddd.copy()
test = pd.merge(test, seed, on='SEED', how = 'left', suffixes= (None, " SEED"))
test = pd.merge(test, team, on='TEAM', how = 'left', suffixes= (None, " TEAM"))

In [11]:
test

,YEAR,CONF,CONF ID,QUAD NO,QUAD ID,TEAM NO,TEAM ID,TEAM,SEED,ROUND,...,R64 TEAM,R32 TEAM,S16 TEAM,E8 TEAM,F4 TEAM,F2 TEAM,CHAMP TEAM,TOP2 TEAM,F4%,CHAMP% TEAM
0,2008,A10,1,1,1,1,244,Xavier,3,8,...,10.0,9.0,7.0,2.0,0.0,0.0,0.0,2.0,51.90%,8.70%
1,2008,A10,1,1,1,1,244,Xavier,3,8,...,10.0,9.0,7.0,2.0,0.0,0.0,0.0,2.0,51.90%,8.70%
2,2008,A10,1,1,1,1,244,Xavier,3,8,...,10.0,9.0,7.0,2.0,0.0,0.0,0.0,2.0,51.90%,8.70%
3,2008,A10,1,1,1,1,244,Xavier,3,8,...,10.0,9.0,7.0,2.0,0.0,0.0,0.0,2.0,51.90%,8.70%
4,2008,B10,6,3,3,2,240,Wisconsin,3,16,...,13.0,11.0,7.0,2.0,2.0,1.0,0.0,2.0,81.40%,31.10%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2084,2024,P12,24,63,3,1077,8,Arizona,2,0,...,11.0,7.0,7.0,3.0,0.0,0.0,0.0,5.0,83.50%,36.10%
2085,2024,SEC,28,63,3,1078,3,Alabama,4,0,...,5.0,3.0,2.0,0.0,0.0,0.0,0.0,2.0,48.40%,15.40%
2086,2024,SEC,28,63,3,1078,3,Alabama,4,0,...,5.0,3.0,2.0,0.0,0.0,0.0,0.0,2.0,48.40%,15.40%
2087,2024,SEC,28,63,3,1078,3,Alabama,4,0,...,5.0,3.0,2.0,0.0,0.0,0.0,0.0,2.0,48.40%,15.40%
2088,2024,MAC,17,61,1,1079,2,Akron,14,0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.50%,0.00%

In [12]:
clean_d = test.copy()

In [180]:
predictors = []
for column in test.columns:
    try:
        val = test[[column, "ROUND"]].corr()["ROUND"].iloc[0]
        if val > 0.35:
            print(f'{column}: {val}         {pd.isnull(clean_d[column]).sum()}')
            predictors.append(column)
    except:
        pass

KADJ O: 0.35697688348700657         0
KADJ EM: 0.4450536554427104         0
BADJ EM: 0.4713979675741528         0
BADJ O: 0.4039324758301799         0
BARTHAG: 0.40697321931978075         0
WAB: 0.40904381599350614         0
OP FT% RANK: 0.3672236731135794         0
POWER: 0.44081748844698637         0
POWER-PATH: 0.4430326063671559         0
WIN% SEED: 0.39307033270276376         0
R32: 0.38576142945840486         0
PAKE TEAM: 0.5174369827000117         0
PASE TEAM: 0.5593863188915591         0
W TEAM: 0.35811291403183393         0
WIN% TEAM: 0.6086458595255962         0
E8 TEAM: 0.3634323966773929         0
F4 TEAM: 0.4494500403018415         0
F2 TEAM: 0.4612429075406296         0
CHAMP TEAM: 0.3989613908523687         0

In [14]:
pd.reset_option('display.max_columns')

In [15]:
clean_d = clean_d.loc[(clean_d['ROUND'] != 68) & (clean_d['ROUND'] != 0)]
clean_d = clean_d.loc[clean_d['YEAR'] > 2012]

In [16]:
clean_d = clean_d.drop(columns = ["POWER RATING", "POWER RATING RANK", "WINS", "BY ROUND NO"])

In [22]:
predictors.remove("BY ROUND NO")

In [23]:
clean_d['PREV ROUND'] = pd.to_numeric(clean_d['PREV ROUND'], errors='coerce')

clean_d['PREV ROUND'] = 7 - np.log2(clean_d['PREV ROUND'])

In [24]:
clean_d["ROUND"] = 7 -np.log2(clean_d["ROUND"])

In [178]:
predictors

['K OFF',
 'KADJ O',
 'KADJ EM',
 'BADJ EM',
 'BADJ O',
 'BARTHAG',
 'WIN%',
 'TALENT',
 'PPPO',
 'ELITE SOS',
 'WAB',
 'POWER',
 'POOL VALUE',
 'POWER-PATH',
 'GAMES SEED',
 'W SEED',
 'WIN% SEED',
 'R32',
 'S16',
 'E8',
 'F4',
 'F2',
 'CHAMP',
 'TOP2',
 'PAKE TEAM',
 'PASE TEAM',
 'GAMES TEAM',
 'W TEAM',
 'L TEAM',
 'WIN% TEAM',
 'R64 TEAM',
 'R32 TEAM',
 'S16 TEAM',
 'E8 TEAM',
 'F4 TEAM',
 'F2 TEAM',
 'CHAMP TEAM',
 'TOP2 TEAM']

In [25]:
train = clean_d[clean_d["YEAR"] < 2023].copy()
test = clean_d[clean_d["YEAR"] == 2023].copy()

In [26]:
predictors.remove("BY ROUND NO")

ValueError: list.remove(x): x not in list

In [27]:
pd.isnull(train[predictors]).sum()

SEED              0
KADJ O RANK       0
KADJ D            0
KADJ D RANK       0
KADJ EM RANK      0
BADJ D            0
BADJ EM RANK      0
BADJ O RANK       0
BADJ D RANK       0
BARTHAG RANK      0
TALENT RANK       0
ELITE SOS RANK    0
PATH              0
POOL S-RANK       0
NCAA S-RANK       0
PREV SEED         0
PREV ROUND        0
L SEED            0
PAKE RANK TEAM    0
dtype: int64

In [28]:
from sklearn.linear_model import Ridge

reg =Ridge(alpha=.1)

In [29]:
reg.fit(train[predictors], train["ROUND"])

Ridge(alpha=0.1)

In [30]:
prediction = reg.predict(test[predictors])

In [31]:
prediction = pd.DataFrame(prediction, columns=['PREDICTIONS'], index =test.index)

In [32]:
pd.reset_option("display.max_rows")
prediction

      PREDICTIONS
1811     3.698719
1812     3.698719
1813     3.698719
1814     1.860184
1815     1.768870
...           ...
1936     0.990261
1937     2.674522
1938     4.350764
1939     4.350764
1940     4.350764

[126 rows x 1 columns]

In [33]:
comb = pd.concat([test[["TEAM", "ROUND"]], prediction], axis=1)

In [34]:
pd.set_option("display.max_rows", None)
comb

                        TEAM  ROUND  PREDICTIONS
1811                  Xavier    3.0     3.698719
1812                  Xavier    3.0     3.698719
1813                  Xavier    3.0     3.698719
1814           West Virginia    1.0     1.860184
1815                Virginia    1.0     1.768870
1816                 Vermont    1.0     1.270582
1817                     VCU    1.0     1.391258
1818                Utah St.    1.0     1.939433
1819                     USC    1.0     2.286914
1820           UNC Asheville    1.0     0.669093
1821                    UCLA    3.0     4.195237
1822                    UCLA    3.0     4.195237
1823                    UCLA    3.0     4.195237
1824        UC Santa Barbara    1.0     0.485509
1826  Texas A&M Corpus Chris    1.0     1.112032
1827               Texas A&M    1.0     3.137537
1828                   Texas    4.0     2.477550
1829                   Texas    4.0     2.477550
1830                   Texas    4.0     2.477550
1831                   Texas    4.0     2.477550
1832               Tennessee    3.0     3.264616
1833               Tennessee    3.0     3.264616
1834               Tennessee    3.0     3.264616
1835                     TCU    2.0     1.955276
1836                     TCU    2.0     1.955276
1838           San Diego St.    6.0     2.980544
1839           San Diego St.    6.0     2.980544
1840           San Diego St.    6.0     2.980544
1841           San Diego St.    6.0     2.980544
1842           San Diego St.    6.0     2.980544
1843           San Diego St.    6.0     2.980544
1844            Saint Mary's    2.0     2.099268
1845            Saint Mary's    2.0     2.099268
1846                  Purdue    1.0     3.765618
1847              Providence    1.0     1.602837
1848               Princeton    3.0     1.833262
1849               Princeton    3.0     1.833262
1850               Princeton    3.0     1.833262
1851              Pittsburgh    2.0     1.570368
1852              Pittsburgh    2.0     1.570368
1853                Penn St.    2.0     2.184831
1854                Penn St.    2.0     2.184831
1855            Oral Roberts    1.0     1.894453
1856            Northwestern    2.0     2.290140
1857            Northwestern    2.0     2.290140
1858       Northern Kentucky    1.0     0.883255
1859      North Carolina St.    1.0     2.147367
1861             Montana St.    1.0     1.165446
1862                Missouri    2.0     1.038742
1863                Missouri    2.0     1.038742
1865            Michigan St.    3.0     3.389575
1866            Michigan St.    3.0     3.389575
1867            Michigan St.    3.0     3.389575
1868                Miami FL    5.0     2.264216
1869                Miami FL    5.0     2.264216
1870                Miami FL    5.0     2.264216
1871                Miami FL    5.0     2.264216
1872                Miami FL    5.0     2.264216
1873                 Memphis    1.0     1.745547
1874                Maryland    2.0     2.731180
1875                Maryland    2.0     2.731180
1876               Marquette    2.0     2.374685
1877               Marquette    2.0     2.374685
1878     Louisiana Lafayette    1.0     0.996655
1879                Kentucky    2.0     4.618493
1880                Kentucky    2.0     4.618493
1881                Kent St.    1.0     1.443873
1882            Kennesaw St.    1.0     1.383926
1883              Kansas St.    4.0     3.501709
1884              Kansas St.    4.0     3.501709
1885              Kansas St.    4.0     3.501709
1886              Kansas St.    4.0     3.501709
1887                  Kansas    2.0     3.927243
1888                  Kansas    2.0     3.927243
1889                Iowa St.    1.0     1.614700
1890                    Iowa    1.0     1.618319
1891                    Iona    1.0     0.816390
1892                 Indiana    2.0     2.475951
1893                 Indiana    2.0     2.475951
1894                Illinois    1.0     1.641000
1895                  Howard    1.0     1.310333
1896                 Houston    3.0     4.785811
1897                 Houston    3.0     4.785811
1898                 Houston    3.0     4.785811
1899            Grand Canyon    1.0     1.231365
1900                 Gonzaga    4.0     4.002760
1901                 Gonzaga    4.0     4.002760
1902                 Gonzaga    4.0     4.002760
1903                 Gonzaga    4.0     4.002760
1904                  Furman    2.0     2.323575
1905                  Furman    2.0     2.323575
1906        Florida Atlantic    5.0     3.132398
1907        Florida Atlantic    5.0     3.132398
1908        Florida Atlantic    5.0     3.132398
1909        Florida Atlantic    5.0     3.132398
1910        Florida Atlantic    5.0     3.132398
1911     Fairleigh Dickinson    2.0     1.405035
1912     Fairleigh Dickinson    2.0     1.405035
1913                    Duke    2.0     3.250461
1914                    Duke    2.0     3.250461
1915                   Drake    1.0     1.135792
1916               Creighton    4.0     3.510752
1917               Creighton    4.0     3.510752
1918               Creighton    4.0     3.510752
1919               Creighton    4.0     3.510752
1920             Connecticut    7.0     4.697859
1921             Connecticut    7.0     4.697859
1922             Connecticut    7.0     4.697859
1923             Connecticut    7.0     4.697859
1924             Connecticut    7.0     4.697859
1925             Connecticut    7.0     4.697859
1926   College of Charleston    1.0     1.583831
1927                 Colgate    1.0     0.898022
1928               Boise St.    1.0     1.834431
1929                  Baylor    2.0     4.125768
1930                  Baylor    2.0     4.125768
1931                  Auburn    2.0     3.505522
1932                  Auburn    2.0     3.505522
1933                Arkansas    3.0     3.422672
1934                Arkansas    3.0     3.422672
1935                Arkansas    3.0     3.422672
1936             Arizona St.    1.0     0.990261
1937                 Arizona    1.0     2.674522
1938                 Alabama    3.0     4.350764
1939                 Alabama    3.0     4.350764
1940                 Alabama    3.0     4.350764

In [35]:
from sklearn.metrics import mean_squared_error

In [36]:
mean_squared_error(comb["ROUND"], comb["PREDICTIONS"])

np.float64(1.9606905334855433)

In [37]:
years = list(range(2013,2024))
years.remove(2020)

In [38]:
comb = comb.drop_duplicates(subset="TEAM", keep= "first")
comb.sort_values(by="PREDICTIONS", ascending = False)

                        TEAM  ROUND  PREDICTIONS
1896                 Houston    3.0     4.785811
1920             Connecticut    7.0     4.697859
1879                Kentucky    2.0     4.618493
1938                 Alabama    3.0     4.350764
1821                    UCLA    3.0     4.195237
1929                  Baylor    2.0     4.125768
1900                 Gonzaga    4.0     4.002760
1887                  Kansas    2.0     3.927243
1846                  Purdue    1.0     3.765618
1811                  Xavier    3.0     3.698719
1916               Creighton    4.0     3.510752
1931                  Auburn    2.0     3.505522
1883              Kansas St.    4.0     3.501709
1933                Arkansas    3.0     3.422672
1865            Michigan St.    3.0     3.389575
1832               Tennessee    3.0     3.264616
1913                    Duke    2.0     3.250461
1827               Texas A&M    1.0     3.137537
1906        Florida Atlantic    5.0     3.132398
1838           San Diego St.    6.0     2.980544
1874                Maryland    2.0     2.731180
1937                 Arizona    1.0     2.674522
1828                   Texas    4.0     2.477550
1892                 Indiana    2.0     2.475951
1876               Marquette    2.0     2.374685
1904                  Furman    2.0     2.323575
1856            Northwestern    2.0     2.290140
1819                     USC    1.0     2.286914
1868                Miami FL    5.0     2.264216
1853                Penn St.    2.0     2.184831
1859      North Carolina St.    1.0     2.147367
1844            Saint Mary's    2.0     2.099268
1835                     TCU    2.0     1.955276
1818                Utah St.    1.0     1.939433
1855            Oral Roberts    1.0     1.894453
1814           West Virginia    1.0     1.860184
1928               Boise St.    1.0     1.834431
1848               Princeton    3.0     1.833262
1815                Virginia    1.0     1.768870
1873                 Memphis    1.0     1.745547
1894                Illinois    1.0     1.641000
1890                    Iowa    1.0     1.618319
1889                Iowa St.    1.0     1.614700
1847              Providence    1.0     1.602837
1926   College of Charleston    1.0     1.583831
1851              Pittsburgh    2.0     1.570368
1881                Kent St.    1.0     1.443873
1911     Fairleigh Dickinson    2.0     1.405035
1817                     VCU    1.0     1.391258
1882            Kennesaw St.    1.0     1.383926
1895                  Howard    1.0     1.310333
1816                 Vermont    1.0     1.270582
1899            Grand Canyon    1.0     1.231365
1861             Montana St.    1.0     1.165446
1915                   Drake    1.0     1.135792
1826  Texas A&M Corpus Chris    1.0     1.112032
1862                Missouri    2.0     1.038742
1878     Louisiana Lafayette    1.0     0.996655
1936             Arizona St.    1.0     0.990261
1927                 Colgate    1.0     0.898022
1858       Northern Kentucky    1.0     0.883255
1891                    Iona    1.0     0.816390
1820           UNC Asheville    1.0     0.669093
1824        UC Santa Barbara    1.0     0.485509

In [98]:
def scorer1(comb):
    comb_u = comb[comb["ROUND"] == round(comb["PREDICTIONS"])]
    s = 0
    for pred in comb_u["ROUND"]:
        val = pred
        if pred != 1:
            while val > 0:
                s += 2**(val-1)
                val -= 1            
    return s

def scorer2(comb):
    comb_u = comb[comb["ROUND"] <= round(comb["PREDICTIONS"])]
    s = 0
    for pred in comb_u["ROUND"]:
        val = pred
        if pred == 1:
            s += 1
        else:
            while val > 0:
                s += 2**(val-1)
                val -= 1
    return s/2

def diff(comb):
    comb["DIFF"] = abs(comb["ROUND"] - round(comb["PREDICTIONS"]))
    return comb["DIFF"].sum()/64

def corr(comb):
    return len(comb[comb["ROUND"] == round(comb["PREDICTIONS"])])/64
def maxdiff(comb):
    comb["DIFF"] = abs(comb["ROUND"] - round(comb["PREDICTIONS"]))
    return max(comb["DIFF"])
diff(comb)

np.float64(0.8125)

In [40]:
aps = []
score = []
all_predictions = []
diffs = []
farthest = []
correct = []
for year in years[2:]:
    print(year)
    train = clean_d[(clean_d["YEAR"] < year)]
    test = clean_d[clean_d["YEAR"] == year]
    reg.fit(train[predictors], train["ROUND"])
    prediction = reg.predict(test[predictors])
    prediction = pd.DataFrame(prediction, columns=['PREDICTIONS'], index =test.index)
    comb = pd.concat([test[["TEAM", "ROUND", "YEAR"]], prediction], axis=1)
    comb = comb.drop_duplicates(subset="TEAM", keep= "first")
    score.append(scorer1(comb))
    diffs.append(diff(comb))
    farthest.append(maxdiff(comb))
    all_predictions.append(comb)
    correct.append(corr(comb))
    aps.append(mean_squared_error(comb["ROUND"], comb["PREDICTIONS"]))

2015
2016
2017
2018
2019
2021
2022
2023

In [41]:
sum(aps) / len(aps)

np.float64(1.184269068573937)

In [42]:
aps

[np.float64(1.248370094612452),
 np.float64(1.1375258998339473),
 np.float64(0.9806053572213571),
 np.float64(1.1904099036832005),
 np.float64(1.1637707053738928),
 np.float64(1.1507981270663425),
 np.float64(1.2940400668103371),
 np.float64(1.3086323939899658)]

In [43]:
diffs

[np.float64(0.8125),
 np.float64(0.84375),
 np.float64(0.6875),
 np.float64(0.734375),
 np.float64(0.796875),
 np.float64(0.828125),
 np.float64(0.84375),
 np.float64(0.8125)]

In [44]:
score

[90.0, 85.0, 110.0, 85.0, 88.0, 65.0, 32.0, 90.0]

In [45]:
[77.0, 92.0, 90.5, 76.0, 101.0, 62.0, 86.0, 73.0]
farthest

[3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0]

In [165]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=50, random_state=1, min_samples_split=10)

In [166]:
def backtest(data, model, predictors):
    aps = []
    score = []
    all_predictions = []
    diffs = []
    farthest = []
    correct = []
    for year in years[2:]:
        print(year)
        train = data[(data["YEAR"] < year)]
        test = data[data["YEAR"] == year]
        model.fit(train[predictors], train["ROUND"])
        prediction = model.predict(test[predictors])
        prediction = pd.DataFrame(prediction, columns=['PREDICTIONS'], index =test.index)
        comb = pd.concat([test[["TEAM", "ROUND", "YEAR"]], prediction], axis=1)
        comb = comb.drop_duplicates(subset="TEAM", keep= "first")
        score.append(scorer1(comb))
        diffs.append(diff(comb))
        farthest.append(maxdiff(comb))
        all_predictions.append(comb)
        correct.append(corr(comb))
        aps.append(mean_squared_error(comb["ROUND"], comb["PREDICTIONS"]))
        
    error_ext = {
        "meansquared" : [(sum(aps)/len(aps)), aps],
        "scores" : [(sum(score)/len(score)), score],
        "differences" : [(sum(diffs)/len(diffs)), diffs],
        "correct predictions" : [(sum(correct)/len(correct)), correct],
        "worst prediction" : farthest
    }
    error_min = [(sum(correct)/len(correct)), (sum(aps)/len(aps)), (sum(score)/len(score)), (sum(diffs)/len(diffs)), sum(farthest)]
    
    return all_predictions, error_ext, error_min

In [174]:
predicts, error, error_min = backtest(clean_d, rf, predictors)

2015
2016
2017
2018
2019
2021
2022
2023

In [175]:
error

{'meansquared': [np.float64(1.1630597561742235),
  [np.float64(0.8445480269213844),
   np.float64(1.6477930438528965),
   np.float64(1.2720624823548914),
   np.float64(1.077146246229821),
   np.float64(1.0076673472156694),
   np.float64(1.041541787056898),
   np.float64(1.3598243622067727),
   np.float64(1.0538947535554546)]],
 'scores': [72.375, [103.0, 46.0, 99.0, 47.0, 79.0, 63.0, 91.0, 51.0]],
 'differences': [np.float64(0.7109375),
  [np.float64(0.640625),
   np.float64(0.875),
   np.float64(0.703125),
   np.float64(0.78125),
   np.float64(0.65625),
   np.float64(0.734375),
   np.float64(0.671875),
   np.float64(0.625)]],
 'correct predictions': [0.498046875,
  [0.5, 0.421875, 0.546875, 0.4375, 0.5, 0.46875, 0.578125, 0.53125]],
 'worst prediction': [3.0, 4.0, 4.0, 3.0, 3.0, 3.0, 4.0, 4.0]}

In [173]:
predictors

['K OFF',
 'KADJ O',
 'KADJ EM',
 'BADJ EM',
 'BADJ O',
 'BARTHAG',
 'WIN%',
 'TALENT',
 'PPPO',
 'ELITE SOS',
 'WAB',
 'POWER',
 'POOL VALUE',
 'POWER-PATH',
 'DUNKS SHARE',
 'CLOSE TWOS FG%',
 'PREV ROUND',
 'PAKE',
 'GAMES SEED',
 'W SEED',
 'WIN% SEED',
 'R32',
 'S16',
 'E8',
 'F4',
 'F2',
 'CHAMP',
 'TOP2',
 'PAKE TEAM',
 'PASE TEAM',
 'GAMES TEAM',
 'W TEAM',
 'L TEAM',
 'WIN% TEAM',
 'R64 TEAM',
 'R32 TEAM',
 'S16 TEAM',
 'E8 TEAM',
 'F4 TEAM',
 'F2 TEAM',
 'CHAMP TEAM',
 'TOP2 TEAM']

In [94]:
predicts, error, error_min = backtest(clean_d, reg, predictors)

2015
2016
2017
2018
2019
2021
2022
2023

In [95]:
error_min

[np.float64(1.184269068573937), 80.625, np.float64(0.794921875), 23.0]